const HolidayData: any[] = [
  {
    id: 71,
    name: "New Years Day",
    blockDate: "1st",
    blockMonth: "January, 2025",
    date: "01/01/2025",
    day: "Wednesday",
  },
  {
    id: 1,
    name: "Martin Luther King Jr. Day",
    blockDate: "20th",
    blockMonth: "January, 2025",
    date: "01/20/2025",
    day: "Monday",
  },
  {
    id: 2,
    name: "President's Day",
    blockDate: "17th",
    blockMonth: "February, 2025",
    date: "02/17/2025",
    day: "Monday",
  },
  {
    id: 21,
    name: "Memorial Day",
    blockDate: "26th",
    blockMonth: "May, 2025",
    date: "05/26/2025",
    day: "Monday",
  },
  {
    id: 3,
    name: "Independence Day",
    blockDate: "4th",
    blockMonth: "July, 2025",
    date: "07/04/2025",
    day: "Friday",
  },
  {
    id: 4,
    name: "Labor Day",
    blockDate: "1st",
    blockMonth: "September, 2025",
    date: "09/01/2025",
    day: "Monday",
  },
  {
    id: 5,
    name: "Thanksgiving",
    blockDate: "27th",
    blockMonth: "November, 2025",
    date: "11/27/2025 & 11/28/2025",
    day: "Thursday & Friday",
  },
  {
    id: 6,
    name: "Christmas Day",
    blockDate: "25th",
    blockMonth: "December, 2025",
    date: "12/25/2025",
    day: "Thursday",
  },
  {
    id: 7,
    name: "New Years Eve (Half Day)",
    blockDate: "31st",
    blockMonth: "December, 2025",
    date: "12/31/2025",
    day: "Wednesday",
  },
];

export default HolidayData;
