export const doctorData = [
  {
    id: 1,
    slug: "a",
    First_Name: "Taha",
    Last_Name: "Ahmed",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English", "Arabic", "Spanish"],
    Specialty: "Pediatrician",
    Organization: "HAVEN PEDIATRICS AND ADOLESCENT CARE, INC.",
    Address: {
      Street: "4950 San Bernardino Street",
      Suite: "Suite 216",
      City: "Montclair",
      State: "CA",
      Zip: "91763",
  
    },
    Phone: "(909) 399-5944",
    Fax: "(909) 399-5669",
    img:"/images/providersphoto/Taha_Ahmed.jpg"
   
  },

  {
    id: 4,
    First_Name: "Sachin",
    Last_Name: "Chatta",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English"],
    Specialty: "Internal Medicine",
    Organization: "Cajon Medical Group PC",
    Address: {
      Street: "12555 Central Avenue",
      Suite: "Suite A",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 735-2446",
    Fax: "(909) 206-1553",
    img:"/images/providersphoto/sampledoc1.jpg"
  },
  {
    id: 5,
    First_Name: "Balu",
    Last_Name: "Gadhe",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English"],
    Specialty: "Internal Medicine",
    Organization: "Cajon Medical Group PC",
    Address: {
      Street: "12555 Central Avenue",
      Suite: "Suite A",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 735-2446",
    Fax: "(909) 206-1553",
   img:"/images/providersphoto/Balu_Gadhe_MD.jpg"
  },
  {
    id: 6,
    First_Name: "Maria",
    Last_Name: "Garcia De Benitez",
    Degree: "M.D.",
    Gender: "F",
    Languages: ["English"],
    Specialty: "Internal Medicine",
    Organization: "Cajon Medical Group PC",
    Address: {
      Street: "12555 Central Avenue",
      Suite: "Suite A",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 735-2446",
    Fax: "(909) 206-1553",
   img:"/images/providersphoto/sampledoc1.jpg"
  },
  {
    id: 7,
    First_Name: "Laurentiu",
    Last_Name: "Istrate",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English"],
    Specialty: "Family Medicine",
    Organization: "Cajon Medical Group PC",
    Address: {
      Street: "12555 Central Avenue",
      Suite: "Suite A",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 735-2446",
    Fax: "(909) 206-1553",
     img:"/images/providersphoto/sampledoc1.jpg"
  },
  {
    id: 8,
    First_Name: "Jose",
    Last_Name: "Lira",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English", "Spanish"],
    Specialty: "Internal Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "5475 Walnut Avenue",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 591-6446",
    Fax: "(909) 591-1309",
    img:"/images/providersphoto/Lira.jpg"
  },
  {
    id: 9,
    First_Name: "Hedy",
    Last_Name: "Loa",
    Degree: "M.D.",
    Gender: "F",
    Languages: ["English", "Indonesian"],
    Specialty: ["Internal Medicine", "Geriatric Medicine"],
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "1131 W. Sixth Street",
      Suite: "Suite 150",
      City: "Ontario",
      State: "CA",
      Zip: "91762",
    },
    Phone: "(909) 482-4462",
    Fax: "(909) 482-4485",
   img:"/images/providersphoto/Hedy_Loa_MD.jpg"
  },
  {
    id: 10,
    First_Name: "Hetalben",
    Last_Name: "Makwana",
    Degree: "M.D.",
    Gender: "F",
    Languages: ["English", "Hindi", "Gujarati"],
    Specialty: "Internal Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "9190 Haven Avenue",
      Suite: "Suite 102",
      City: "Rancho Cucamonga",
      State: "CA",
      Zip: "91730",
    },
    Phone: "(909) 981-0989",
    Fax: "(909) 949-6214",
  img:"/images/providersphoto/Hetalben_Makwana.jpg"
  },
  {
    id: 11,
    First_Name: "Usha",
    Last_Name: "Mantha",
    Degree: "M.D.",
    Gender: "F",
    Languages: ["English", "Hindi", "Telugu"],
    Specialty: "Family Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "1131 W. Sixth Street",
      Suite: "Suite 150",
      City: "Ontario",
      State: "CA",
      Zip: "91762",
    },
    Phone: "(909) 482-4462",
    Fax: "(909) 482-4485",
   img:"/images/providersphoto/Usha_Mantha_MD.jpg"
  },
  {
    id: 12,
    First_Name: "Avani",
    Last_Name: "Patel Shah",
    Degree: "M.D.",
    Gender: "F",
    Languages: ["English", "Gujarati", "Spanish"],
    Specialty: "Internal Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "5475 Walnut Avenue",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 591-6446",
    Fax: "(909) 591-1309",
    img:"/images/providersphoto/Avani_Patel_Shah_MD.jpg"
  },
  {
    id: 13,
    First_Name: "Venkata",
    Last_Name: "Pulakanti",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English", "Hindi", "Telugu"],
    Specialty: "Internal Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "9190 Haven Avenue",
      Suite: "Suite 102",
      City: "Rancho Cucamonga",
      State: "CA",
      Zip: "91730",
    },
    Phone: "(909) 296-7800",
    Fax: "(909) 509-5511",
    img:"/images/providersphoto/Venkat_Pulakanti_MD.jpg"
  },
  {
    id: 14,
    First_Name: "Nayan",
    Last_Name: "Shah",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English", "Telegu"],
    Specialty: "Family Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
      Street: "5475 Walnut Avenue",
      City: "Chino",
      State: "CA",
      Zip: "91710",
    },
    Phone: "(909) 591-6446",
    Fax: "(909) 591-1309",
    img:"/images/providersphoto/Nayan.jpg"
  },
  {
    id: 15,
    First_Name: "Hamed",
    Last_Name: "Shalikar",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English"],
    Specialty: "Family Medicine",
    Organization: "Desert Valley Medical Group, Inc., dba Chino Valley Primary Care",
    Address: {
        Street: "5450 Jefferson Avenue",
        Suite: "Suite 3",
        City: "Chino",
        State: "CA",
        Zip: "91710"
    },
    Phone: "(909) 464-8722",
    Fax: "(909) 464-8737",
    img:"/images/providersphoto/Hamed_Shalikar_MD.jpg"
},
{id: 16,
    First_Name: "Tejinder",
    Last_Name: "Singh",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English", "Hindi"],
    Specialty: "Internal Medicine",
    Organization: "MY FAMILY MEDICAL GROUP",
    Address: {
        Street: "914 W. Foothill Blvd.",
        Suite: "Suite B",
        City: "Upland",
        State: "CA",
        Zip: "91786"
    },
    Phone: "(909) 982-8944",
    Fax: "(909) 985-0932",
     img:"/images/providersphoto/sampledoc1.jpg"
},
{
  id: 17,
    First_Name: "Mehul",
    Last_Name: "Sonawala",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English"],
    Specialty: "Internal Medicine",
    Organization: "Cajon Medical Group PC",
    Address: {
        Stree: "12555 Central Avenue",
        Suite: "Suite A",
        City: "Chino",
        State: "CA",
        Zip: "91710"
    },
    Phone: "(909) 735-2446",
    Fax: "(909) 206-1553",
     img:"/images/providersphoto/sampledoc1.jpg"
},
{id: 18,
    First_Name: "Thillaiampalam",
    Last_Name: "Sri Jaerajah",
    Degree: "M.D.",
    Gender: "M",
    Languages: ["English"],
    Specialty: "Internal Medicine",
    Organization: "Cajon Medical Group PC",
    Address: {
        Street: "12555 Central Avenue",
        Suite: "Suite A",
        City: "Chino",
        State: "CA",
        Zip: "91710"
    },
    Phone: "(909) 735-2446",
    Fax: "(909) 206-1553",
    img:"/images/providersphoto/sampledoc1.jpg"
}

];
